---
title: "testing"
author: "Carey LeMesurier"
date: "09/03/2022"
output: html_document
---

```{r setup, include=FALSE}
library(shiny)
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(bslib)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r data}
# load our data -----------------------------------------------------------
# national level statistics  ----------------------------------------------
scotland_df <- read_csv('data/scotland.csv')
england_df <- read_csv('data/england.csv')
wales_df <- read_csv("data/wales.csv")
north_df <- read_csv("data/north_ireland.csv")

# city level statistics  ---------------------------------------------------
belfast_df <- read_csv("data/belfast.csv")
belfast_df <- merge(belfast_df[, !names(belfast_df) %in% c('hospitalCases')], select(north_df, c('date','hospitalCases')), by='date')
#belfast_df$hospitalCases = north_df$hospitalCases

cardiff_df <- read_csv("data/cardiff.csv")
cardiff_df <- merge(cardiff_df[, !names(cardiff_df) %in% c('hospitalCases')], select(wales_df, c('date','hospitalCases')), by='date')
names(cardiff_df)[names(cardiff_df) == 'cumDeaths28DaysByPublishDate'] <- "cumDeaths28DaysByDeathDate"
#cardiff_df$hospitalCases = wales_df$hospitalCases

edinburgh_df <- read_csv("data/edinburgh.csv")
edinburgh_df <- merge(edinburgh_df[, !names(edinburgh_df) %in% c('hospitalCases')], select(scotland_df, c('date','hospitalCases')), by='date')
#edinburgh_df$hospitalCases = scotland_df$hospitalCases

birmingham_df <- read_csv("data/birmingham.csv")
birmingham_df <- merge(birmingham_df[, !names(birmingham_df) %in% c('hospitalCases')], select(england_df, c('date','hospitalCases')), by='date')
#birmingham_df$hospitalCases = england_df$hospitalCases

bristol_df <- read_csv("data/bristol.csv")
bristol_df <- merge(bristol_df[, !names(bristol_df) %in% c('hospitalCases')], select(england_df, c('date','hospitalCases')), by='date')
#bristol_df$hospitalCases = england_df$hospitalCases

cambridge_df <- read_csv("data/cambridge.csv")
cambridge_df <- merge(cambridge_df[, !names(cambridge_df) %in% c('hospitalCases')], select(england_df, c('date','hospitalCases')), by='date')
#cambridge_df$hospitalCases = england_df$hospitalCases

glasgow_df <- read_csv("data/glasgow.csv")
glasgow_df <- merge(glasgow_df[, !names(glasgow_df) %in% c('hospitalCases')], select(scotland_df, c('date','hospitalCases')), by='date')
#glasgow_df$hospitalCases = scotland_df$hospitalCases

# change date columns to date type
cities <- list(belfast_df, cardiff_df, edinburgh_df, birmingham_df, bristol_df, cambridge_df, glasgow_df)
for (city_df in cities){
    city_df <- city_df %>%
        mutate(date = as.Date(date, format= "%Y-%m-%d"))
}

# vaccine data  -----------------------------------------------------------
belfast_vac_df <- read_csv("data/belfast_vac.csv")
cardiff_vac_df <- read_csv("data/cardiff_vac.csv")
edinburgh_vac_df <- read_csv("data/edinburgh_vac.csv")
birmingham_vac_df <- read_csv("data/birmingham_vac.csv")
bristol_vac_df <- read_csv("data/bristol_vac.csv")
cambridge_vac_df <- read_csv("data/cambridge_vac.csv")
glasgow_vac_df <- read_csv("data/glasgow_vac.csv")
```



```{r}
# This Weeks data -------------------------------------------------------------------
# initialize dataframe with just the headers of a city df
all_cities_df <- belfast_df[0,]

# get latest date in data
today <- max(belfast_df$date)
earliest_date <- today - as.difftime(7, unit="days")

replaceNa <- function(x) {
    idx <- !is.na(x)
    x[idx][cumsum(idx)]
}

# loop through each city df and replace NA with 0 and concatenate the last 7 days data to the last7days_df
for (city_df in cities){
    filtered_data <- city_df %>%
        arrange(date)
    
    # set first row nas to 0
    filtered_data[1,is.na(filtered_data[1,])] <- 0
    
    filtered_data$hospitalCases <- replaceNa(filtered_data$hospitalCases)
    filtered_data$cumCasesByPublishDate <- replaceNa(filtered_data$cumCasesByPublishDate)
    filtered_data$cumDeaths28DaysByDeathDate <- replaceNa(filtered_data$cumDeaths28DaysByDeathDate)
    
    # for daily stats replace nas with 0, and cumulative stats that are all NAs (meaning 0)
    filtered_data[is.na(filtered_data)] <- 0
    
    all_cities_df <- rbind(all_cities_df, filtered_data)
}

last7days_df <- all_cities_df %>%
    filter(date>=earliest_date)

```

```{r}
head(last7days_df,40)
```


```{r}
last7days_df %>% 
    aggregate(newCasesByPublishDate ~ areaName, data=., sum) %>% 
    ggplot(aes(x=areaName,y=newCasesByPublishDate)) +
    geom_bar(stat='identity')+
    labs(title = "Number of Reported Cases per City (in the last week)",
         x = "City",
         y = "Number of Cases")
```

## Map Visual

```{r}
require(maps)
require(viridis)
theme_set(
  theme_void()
  )

```

```{r}
city_nations <- data.frame(matrix(ncol = 2, nrow = 0))
col_names <- c("areaName", "nation")
colnames(city_nations) <- col_names

city_nations[nrow(city_nations) + 1,] <- c('Belfast', 'North Ireland')
city_nations[nrow(city_nations) + 1,] <- c('Cardiff', 'Wales')
city_nations[nrow(city_nations) + 1,] <- c('City of Edinburgh', 'Scotland')
city_nations[nrow(city_nations) + 1,] <- c('Birmingham', 'England')
city_nations[nrow(city_nations) + 1,] <- c('Bristol, City of','England')
city_nations[nrow(city_nations) + 1,] <- c('Cambridgeshire', 'England')
city_nations[nrow(city_nations) + 1,] <- c('Glasgow City', 'Scotland')

```


```{r}
city_locations <- data.frame(matrix(ncol = 3, nrow = 0))
col_names <- c("areaName", "lat", "long")
colnames(city_locations) <- col_names

city_locations[nrow(city_locations) + 1,] <- c('Belfast', 54.5973, -5.9301)
city_locations[nrow(city_locations) + 1,] <- c('Cardiff', 51.4837, -3.1681)
city_locations[nrow(city_locations) + 1,] <- c('City of Edinburgh', 55.9533, -3.1883)
city_locations[nrow(city_locations) + 1,] <- c('Birmingham', 52.4862, -1.8904)
city_locations[nrow(city_locations) + 1,] <- c('Bristol, City of', 51.4545, -2.5879)
city_locations[nrow(city_locations) + 1,] <- c('Cambridgeshire', 52.2053, -0.1218)
city_locations[nrow(city_locations) + 1,] <- c('Glasgow City', 55.8642, -4.2518)
```

```{r}
# get aggregates from last 7 days by city- sums for new cases/deaths, latest value for cumulative data
last7days_df_summarize <- aggregate(cbind(newCasesByPublishDate,newDeaths28DaysByPublishDate)~
                                        areaName, last7days_df, sum) %>% arrange(areaName)

last7days_df_summarize$cumCasesByPublishDate <- (last7days_df %>%
                                                     filter(date == today) %>% 
                                                     arrange(areaName))$cumCasesByPublishDate
last7days_df_summarize$cumDeaths28DaysByDeathDate <- (last7days_df %>%
                                                          filter(date == today) %>%
                                                          arrange(areaName))$cumDeaths28DaysByDeathDate
last7days_df_summarize$hospitalCases <- (last7days_df %>%
                                             filter(date == today) %>% 
                                             arrange(areaName))$hospitalCases
# merge long lat data with last 7 days data
last7days_df_summarize <- merge(last7days_df_summarize, city_locations, by='areaName')

```

```{r}
head(last7days_df_summarize, 7)
```



```{r}
library("cowplot")

world_map <- map_data("world")

last7days_df_summarize$selected = ifelse(last7days_df_summarize$areaName=="Belfast","1","2")

selected_metric="New Cases"
map_p <-ggplot() +
                geom_polygon(data = world_map, 
                             aes(x = long, y = lat, group=group), 
                             fill="lightgrey", colour = "white") + 
                coord_fixed(ratio = 1.3, 
                            xlim = c(-10,3), 
                            ylim = c(50, 59)) + 
                theme_void() +
                geom_point(data = last7days_df_summarize, 
                           aes(x = as.numeric(long), y = as.numeric(lat), 
                               size = newCasesByPublishDate, 
                               colour = selected,
                               text = paste("City: ", areaName, 
                                            "<br>New Cases this week: ", newCasesByPublishDate)))+
                scale_color_manual(guide = "none",
                     values=c("#6bb9fc","black")) +
                scale_size_continuous(name=paste("Number of",selected_metric)) +
                theme(legend.position='right')
               # theme(legend.margin = margin(-10,unit="pt"))

#ggplotly(map_p, tooltip="text")%>%
  #layout(showlegend = FALSE)

legend <- cowplot::get_legend(map_p) 

ggplotly(plot_grid(legend))  #, nrow=1, ncol=1, rel_widths = c(1))

#ggdraw(legend) #+ theme(plot.margin=grid::unit(c(-100,-100,-100,-100), "mm"))


```





```{r}
library(ggpubr)

legend <- cowplot::get_legend(map_p) 

#plot_grid(map_p+theme(legend.position='none'), legend, nrow=1, ncol=2, rel_widths = c(1,0.01)) #+ theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))
#ggplotly(plot_grid(legend))
#ggdraw(legend) #

as_ggplot(legend)


```

```{r}
#library(ggpubr)

```




## line plot

```{r}
selected_city <- "Belfast"
filter_data <- last7days_df %>% 
    filter(areaName == "Belfast")

#head(filter_data)
#theme_set(theme_grey())
#line_p <- 
line_p <- ggplot()+
  geom_line(data=filter_data, aes(x=date,y=newCasesByPublishDate))+
  labs(x = "Date",y = "Number of Cases")

ggplotly(line_p, tooltip="text")
#line_p

```
## Status section


```{r}
# Data From 2 Weeks Ago ---------------------------------------------------------------
#so I can get percent increase from last week to this week 

two_weeks_ago_df <- belfast_df[0,]

# get latest date in data
today <- max(belfast_df$date)
earliest_date <- today - as.difftime(7, unit="days")
two_weeks_ago_date <- today - as.difftime(14, unit="days")

#get data from 2 weeks ago
two_weeks_ago_df <- all_cities_df %>%
    filter(date<=earliest_date,
           date>=two_weeks_ago_date)

two_weeks_ago_df_summarize <- aggregate(cbind(newCasesByPublishDate, newDeaths28DaysByPublishDate)~
                                            areaName, two_weeks_ago_df, sum)%>% arrange(areaName)

two_weeks_ago_df_summarize$cumCasesByPublishDate <- (two_weeks_ago_df %>%
                                                     filter(date == earliest_date)%>% 
                                                         arrange(areaName))$cumCasesByPublishDate
two_weeks_ago_df_summarize$cumDeaths28DaysByDeathDate <- (two_weeks_ago_df %>%
                                                          filter(date == earliest_date)%>% 
                                                              arrange(areaName))$cumDeaths28DaysByDeathDate
two_weeks_ago_df_summarize$hospitalCases <- (two_weeks_ago_df %>%
                                             filter(date == earliest_date)%>% 
                                                 arrange(areaName))$hospitalCases

# percent increase data --------------------------------------------------------------------
col_names <- colnames(two_weeks_ago_df_summarize)
percent_increase_df <- data.frame(matrix(ncol = 6, nrow = 7))
colnames(percent_increase_df) <- col_names

percent_increase_df$newCasesByPublishDate <- ((last7days_df_summarize$newCasesByPublishDate - two_weeks_ago_df_summarize$newCasesByPublishDate)/two_weeks_ago_df_summarize$newCasesByPublishDate)*100
percent_increase_df$newDeaths28DaysByPublishDate <- ((last7days_df_summarize$newDeaths28DaysByPublishDate - two_weeks_ago_df_summarize$newDeaths28DaysByPublishDate)/ two_weeks_ago_df_summarize$newDeaths28DaysByPublishDate)*100
percent_increase_df$hospitalCases <- ((last7days_df_summarize$hospitalCases - two_weeks_ago_df_summarize$hospitalCases)/two_weeks_ago_df_summarize$hospitalCases)*100
percent_increase_df$cumCasesByPublishDate <- ((last7days_df_summarize$cumCasesByPublishDate - two_weeks_ago_df_summarize$cumCasesByPublishDate)/two_weeks_ago_df_summarize$cumCasesByPublishDate)*100
percent_increase_df$cumDeaths28DaysByDeathDate <- ((last7days_df_summarize$cumDeaths28DaysByDeathDate - two_weeks_ago_df_summarize$cumDeaths28DaysByDeathDate)/two_weeks_ago_df_summarize$cumDeaths28DaysByDeathDate)*100
percent_increase_df$areaName <- two_weeks_ago_df_summarize$areaName

is.nan.data.frame <- function(x)
    do.call(cbind, lapply(x, is.nan))

percent_increase_df[is.nan(percent_increase_df)] <- 0


```

## percent tiles


```{r}

percent_increase_df$group <- ifelse(percent_increase_df$newCasesByPublishDate<0,"green","red")
percent_increase_df$label_percent <- round(percent_increase_df$newCasesByPublishDate, digits=0)
percent_increase_df$pos <- ifelse(percent_increase_df$newCasesByPublishDate<0,"","+")



```

```{r}
fig <- plot_ly()
cities = c('Belfast','Birmingham', 'Bristol, City of','Cambridgeshire','Cardiff','City of Edinburgh','Glasgow City')
i <- 1
for (city in cities){
  if (city=='Bristol, City of'){
    city_title<-'Bristol'
  }
  else if (city=='City of Edinburgh'){
    city_title<-'Edinburgh'
  }
  else{
    city_title<-city
  }
  fig <- fig %>%
    add_trace(
      type = "indicator",
      mode = "number",
      value = (percent_increase_df %>% filter(areaName==city))$label_percent,
      number = list(
        prefix = (percent_increase_df %>% filter(areaName==city))$pos,
        suffix="%", 
        font=list(
          color=(percent_increase_df %>% filter(areaName==city))$group,
          size = 25)),
      domain = list(x = c((i-1)/7, i/7), y = c(0, 1)),
      title =list(text = city_title,
                  font=list(
                    color="black",
                    size = 12))
      ) 
  i <- i+1
}

fig

```




```{r}

ggplot(percent_increase_df, aes(fill = group_colour, ymax = newCasesByPublishDate, ymin = 0, xmax = 2, xmin = 1)) +
 geom_rect(aes(ymax=1, ymin=0, xmax=2, xmin=1), fill ="#ece8bd") +
 geom_rect() + 
 coord_polar(theta = "y",start=-pi/2) + xlim(c(0, 2)) + ylim(c(0,2)) +
 geom_text(aes(x = 0, y = 0, label = label_percent, colour=group_colour), size=6.5, family="Poppins SemiBold") +
 geom_text(aes(x=1.5, y=1.5, label=areaName), family="Poppins Light", size=4.2) + 
 facet_wrap(~areaName, ncol = 7) +
 theme_void() +
 scale_fill_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 scale_colour_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 theme(strip.background = element_blank(),
 strip.text.x = element_blank()) +
 guides(fill=FALSE) +
 guides(colour=FALSE)


```




## test

```{r}
df <- data.frame(matrix(nrow=5, ncol = 2))

names(df) <- c("variable", "percentage")
df$variable <- c("Carbohydrates", "Warming", "NGTnotPresent", "DrainNotPresent", "DrEaMing")
df$percentage <- c(0.67,0.33,0.86,0.78,0.58)

df <- df %>% mutate(group=ifelse(percentage <0.6, "red",
 ifelse(percentage>=0.6 & percentage<0.8, "orange","green")),
 label=paste0(percentage*100, "%"),
 title=dplyr::recode(variable, `Carbohydrates`="Preoperative\ncarbohydrate loading",
 `Warming`="Intraoperative\nwarming",
 `NGTnotPresent`="Patients without a\nnasogastric tube\non arrival in recovery",
 `DrainNotPresent`="Patients without an\nabdominal drain\non arrival in recovery",
 `DrEaMing`="Patients DrEaMing on\npostoperative day 1"))

ggplot(df, aes(fill = group, ymax = percentage, ymin = 0, xmax = 2, xmin = 1)) +
 geom_rect(aes(ymax=1, ymin=0, xmax=2, xmin=1), fill ="#ece8bd") +
 geom_rect() + 
 coord_polar(theta = "y",start=-pi/2) + xlim(c(0, 2)) + ylim(c(0,2)) +
 geom_text(aes(x = 0, y = 0, label = label, colour=group), size=6.5, family="Poppins SemiBold") +
 geom_text(aes(x=1.5, y=1.5, label=title), family="Poppins Light", size=4.2) + 
 facet_wrap(~title, ncol = 5) +
 theme_void() +
 scale_fill_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 scale_colour_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 theme(strip.background = element_blank(),
 strip.text.x = element_blank()) +
 guides(fill=FALSE) +
 guides(colour=FALSE)

```


